# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39169cc36f4f4bbcd197742de0f915230aa8db966d2e0ce05f316a993e680574f19c68fa2fddf742a210451a7ccccc7fc630598dc66c521abcea7d73232f863c

test:
  secret_key_base: 2f8690644ffd64582514da9c1c073c2d59c072d27379c165d931685de7b377075e890120df8518bf5b27c06521dea4d523b4c269a6886a342a89173358792fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
